### ISSUE TITLE
enable lidar laser in heron simulation

### ISSUE THREAD

**Issue by anguyen216** [heron/heron#15]
I'm testing some customized program with the heron in simulation.  The heron description files indicated that there's a laser that can be enabled and the laser will publish to `/front/scan` topic.  But I'm unsure on how to enable this laser in simulation.  While the simulation is running, no data is published to `/front/scan` topic and the laser is not visible in simulation either.  I tried to follow the instruction to enable the laser on a jackal (tutorial can be found [here](http://www.clearpathrobotics.com/assets/guides/kinetic/ros/ROS%20Navigation%20Basics.html#customization)).  But this didn't work either.  More specifically, I used the following command to launch gazebo simulation
```
roslaunch heron_gazebo heron_world.launch config:=front_laser
```

I'm running everything on Ubuntu 18.04, ros melodic and gazebo 9.19

Please help.  I need the laser in simulation to use navigation stack

**Comment by civerachb-cpr** [comment]
The Heron doesn't support the same `config:=....` properties as the Jackal.  To add a laser to the Heron the easiest way is to use the `HERON_LASER` environment variable:

```
export HERON_LASER=1
roslaunch heron_gazebo heron_lake_world.launch
```

This will spawn the simulation environment that looks like this with an LMS1xx lidar on the robot:
![gazebo](https://user-images.githubusercontent.com/59611394/139499403-de803193-75e6-4953-a8d7-4354250e2387.png)

In a separate terminal you can open up rviz and use the Add > By Topic > `/front/scan` to add the lidar to the visualization:

```
roslaunch heron_viz view_robot.launch
```

![rviz](https://user-images.githubusercontent.com/59611394/139499491-3034a883-a002-4aae-8eea-1ee84b5177f4.png)

Note that the lidar is above the surface, so the Heron will only be able to "see" objects that protrude above the water.

**Comment by anguyen216** [comment]
That works.  Thank you!
